### ISSUE TITLE
sh: cls: command not found

### ISSUE THREAD

**Issue by serhii-londar** [AlexTrushkovsky/NoWarDDoS#11]
macOS Monstery 12.2.1 (21D62):
sh: cls: command not found

<img width="552" alt="Screenshot 2022-02-27 at 14 34 24" src="https://user-images.githubusercontent.com/15808174/155882510-91bca02a-896d-4ff9-aa45-b3b5fccb5ed2.png">

**Comment by harentius** [comment]
It is already fixed in sources: 
https://github.com/AlexTrushkovsky/NoWarDDoS/blob/main/attack.py#L24
But old version is used, I suppose because of this:
https://gist.githubusercontent.com/AlexTrushkovsky/041d6e2ee27472a69abcb1b2bf90ed4d/raw/nowarversion.json
(https://github.com/AlexTrushkovsky/NoWarDDoS/blob/main/attack.py#L56)

Anyway it still works without cleaning screen, so just keep it running
